apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  namespace: default
spec:
  containers:
  - image: ubuntu
    imagePullPolicy: IfNotPresent
    name: ubuntu
    #env:
    #- name: VAULT_ADDR
    #  value: $VAULT_ADDR
  #serviceAccountName: postgres-vault
